name: Mirror Docker Images to GHCR

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:
    inputs:
      image:
        description: 'Optional: Sync a specific image (e.g., moby/buildkit:latest)'
        required: false
        default: ''

env:
  SINGLE_IMAGE: ${{ github.event.inputs.image }}  # Manual override for one image
  IMAGES: |
    moby/buildkit:latest ghcr.io/${{ github.repository }}/buildkit
    ruby:latest ghcr.io/${{ github.repository }}/ruby
    nginx:latest ghcr.io/${{ github.repository }}/nginx
    node:latest ghcr.io/${{ github.repository }}/nodejs
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Optional Slack webhook

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write  # For better security with OIDC
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq for Rate Limit Check
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check Docker Hub Rate Limits
        run: |
          TOKEN=$(curl -s "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ratelimitcheck/test:pull" | jq -r .token)
          LIMITS=$(curl -s -H "Authorization: Bearer $TOKEN" https://registry-1.docker.io/v2/ratelimitcheck/test/manifests/latest 2>&1 | grep -i 'ratelimit')
          echo "Current Docker Hub rate limits: $LIMITS"
          if [[ $LIMITS == *"429 Too Many Requests"* ]]; then
            echo "Rate limit exceeded, waiting..."
            exit 1
          fi
        continue-on-error: true

      - name: Mirror Single Image (If Provided)
        if: env.SINGLE_IMAGE != ''
        run: |
          echo "Syncing single image: $SINGLE_IMAGE"
          docker pull "$SINGLE_IMAGE" || { echo "Failed to pull $SINGLE_IMAGE"; exit 1; }
          IMAGE_NAME=$(echo "$SINGLE_IMAGE" | awk -F':' '{print $1}')
          TAG=$(echo "$SINGLE_IMAGE" | awk -F':' '{print $2:-"latest"}')
          TARGET="ghcr.io/${{ github.repository }}/$(basename "$IMAGE_NAME"):$TAG"
          docker tag "$SINGLE_IMAGE" "$TARGET"
          docker push "$TARGET" || { echo "Failed to push $TARGET"; exit 1; }
        shell: bash

      - name: Mirror All Images (If No Override)
        if: env.SINGLE_IMAGE == ''
        run: |
          echo "No single image specified. Syncing all predefined images."
          while read -r SOURCE TARGET; do
            echo "Processing $SOURCE -> $TARGET"
            docker pull "$SOURCE" || { echo "Failed to pull $SOURCE"; continue; }
            docker tag "$SOURCE" "$TARGET"
            docker push "$TARGET" || { echo "Failed to push $TARGET"; continue; }
          done <<< "$IMAGES"
        shell: bash

      - name: Notify on Success
        if: success() && env.SLACK_WEBHOOK_URL != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"✅ Successfully mirrored images for ${{ github.repository }}! Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
            "$SLACK_WEBHOOK_URL"
        continue-on-error: true

      - name: Notify on Failure
        if: failure() && env.SLACK_WEBHOOK_URL != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"🚨 Image mirroring failed for ${{ github.repository }}! Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
            "$SLACK_WEBHOOK_URL"
        continue-on-error: true