name: Mirror All Docker Images to GHCR

on:
  workflow_dispatch:  # Manual only, no schedules

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Mirror Images
        env:
          GHCR_PREFIX: ghcr.io/${{ github.repository }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          # Debug info
          echo "Starting mirror process..."
          echo "GHCR_PREFIX: $GHCR_PREFIX"
          
          # Add this before the get_tags function
          debug_curl() {
            echo "Curl command failed. Response: $1"
            echo "HTTP Status: $2"
          }
          
          get_tags() {
            local IMAGE=$1
            local REPO=$2
            echo "Fetching tags for ${REPO}/${IMAGE}..."
            
            # Debug auth attempt
            echo "Attempting to get auth token..."
            
            local AUTH_RESPONSE=$(curl -s -f -w "%{http_code}" \
              -H "Content-Type: application/json" \
              -u "${DOCKERHUB_USERNAME}:${DOCKERHUB_TOKEN}" \
              "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${REPO}/${IMAGE}:pull")
            
            local HTTP_STATUS=${AUTH_RESPONSE: -3}
            local RESPONSE_BODY=${AUTH_RESPONSE:0:${#AUTH_RESPONSE}-3}
            
            if [ "$HTTP_STATUS" != "200" ]; then
              debug_curl "$RESPONSE_BODY" "$HTTP_STATUS"
              return 1
            fi
            
            local TOKEN=$(echo "$RESPONSE_BODY" | jq -r .token)
            
            # Get tags using Docker Hub API v2
            local TAGS=$(curl -s -f -L \
              -H "Accept: application/json" \
              -H "Authorization: Bearer $TOKEN" \
              "https://registry.hub.docker.com/v2/${REPO}/${IMAGE}/tags/list" | \
              jq -r '.tags[]' | \
              grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | \
              sed 's/^v//' | \
              sort -V -r | \
              head -n 3)
            
            if [ -z "$TAGS" ]; then
              echo "No valid tags found for ${REPO}/${IMAGE}"
              return 1
            fi
            
            echo "$TAGS"
          }
          
          mirror_image() {
            local SOURCE=$1
            local TARGET=$2
            echo "Mirroring: $SOURCE -> $TARGET"
            
            if ! docker pull "$SOURCE"; then
              echo "Failed to pull $SOURCE"
              return 1
            fi
            
            docker tag "$SOURCE" "$TARGET"
            
            if ! docker push "$TARGET"; then
              echo "Failed to push $TARGET"
              return 1
            fi
            
            echo "Successfully mirrored $SOURCE -> $TARGET"
          }
          
          # Process each image with retries
          IMAGES=(
            "buildkit:moby/buildkit"
            "ruby:library/ruby"
            "nginx:library/nginx"
            "node:library/node"
          )
          
          for image in "${IMAGES[@]}"; do
            IFS=':' read -r NAME REPO <<< "$image"
            echo "Processing $NAME from $REPO"
            
            # Try to get tags with retries
            for attempt in {1..3}; do
              echo "Attempt $attempt to fetch tags for $NAME"
              TAGS=$(get_tags "$NAME" "$REPO")
              if [ $? -eq 0 ] && [ ! -z "$TAGS" ]; then
                break
              fi
              echo "Attempt $attempt failed, waiting 10s..."
              sleep 10
            done
            
            if [ -z "$TAGS" ]; then
              echo "Failed to get tags for $NAME after 3 attempts"
              continue
            fi
            
            echo "Found tags for $NAME: $TAGS"
            
            # Mirror each version
            echo "$TAGS" | while read -r TAG; do
              if [ ! -z "$TAG" ]; then
                SOURCE="${REPO}/${NAME}:${TAG}"
                TARGET="${GHCR_PREFIX}/${NAME}:${TAG}"
                
                for attempt in {1..3}; do
                  echo "Attempt $attempt to mirror $SOURCE"
                  if mirror_image "$SOURCE" "$TARGET"; then
                    break
                  fi
                  echo "Attempt $attempt failed, waiting 10s..."
                  sleep 10
                done
              fi
            done
            
            # Handle latest tag
            SOURCE="${REPO}/${NAME}:latest"
            TARGET="${GHCR_PREFIX}/${NAME}:latest"
            echo "Mirroring latest tag"
            mirror_image "$SOURCE" "$TARGET"
            
            # Wait between images to avoid rate limits
            sleep 5
          done

      - name: Notify on Success
        if: success() && env.SLACK_WEBHOOK_URL != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"✅ Successfully mirrored all images for ${{ github.repository }}! Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
            "$SLACK_WEBHOOK_URL"
        continue-on-error: true

      - name: Notify on Failure
        if: failure() && env.SLACK_WEBHOOK_URL != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"🚨 All image mirroring failed for ${{ github.repository }}! Check logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}" \
            "$SLACK_WEBHOOK_URL"
        continue-on-error: true