name: Mirror BuildKit Image

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

env:
  SOURCE_IMAGE: moby/buildkit:latest
  TARGET_IMAGE: ghcr.io/${{ github.repository }}/buildkit

jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and push BuildKit image
        run: |
          # Pull the latest BuildKit image
          docker pull ${{ env.SOURCE_IMAGE }}
          
          # Tag for GHCR
          docker tag ${{ env.SOURCE_IMAGE }} ${{ env.TARGET_IMAGE }}
          
          # Push to GHCR
          docker push ${{ env.TARGET_IMAGE }} 